- src/ScreenshotWindow.vala
When taking area screenshot, pointer position was not correct.
Pointer was not clipped properly when positioned on screenshot border.
> Pointer bugfixes

- data/screenshot-tool.appdata.xml.in
- src/ScreenshotWindow.vala
This is intended to resolve #31.
> Remember main window position for reappearing window

- data/screenshot-tool.appdata.xml.in
- src/Screenshot.vala
- src/ScreenshotWindow.vala
- src/Widgets/SaveDialog.vala
This is a suggestion to implement #41
> New default folder to save screenshots

- src/Widgets/SaveDialog.vala
> Get preview image at scale

- src/ScreenshotWindow.vala
> Cancel to close

- src/ScreenshotWindow.vala
> Set opacity to 1 when ESC is hit

- src/Widgets/SaveDialog.vala
> add scale factor into filename

- src/ScreenshotWindow.vala
> Fix radio button spacing

- data/io.elementary.screenshot-tool.gschema.xml
- po/extra/tr.po
- src/ScreenshotWindow.vala
Stores and reloads on startup the last capture mode. So if the user always picks selection, that's what it will default to the next time the app opens
> Restore last capture mode

- src/Application.vala
> Use light style

- src/Widgets/SelectionArea.vala
This property doesn't do anything anymore anyways
> Remove deprecated has_resize_grip

- src/ScreenshotWindow.vala
> Use get_position to get window position

- src/ScreenshotWindow.vala
> Allow to close the app window

- src/ScreenshotWindow.vala
Because errors can happen and it's hard to bring the original font back
> First of all: put the original font back

- src/Application.vala
References #132.
Credit to @peteruithoven for the implementation example.
> Application window closes with "Escape" key

- data/io.elementary.screenshot-tool.appdata.xml.in
This does not contain a release tag intentionally
> AppData: Add 1.7.0 release info

- src/Application.vala
> Application: Remove unused get_instance

- src/Application.vala
And bump copyright header
View with no whitespace changes
> Application: inline screenshot namespace

- src/ScreenshotWindow.vala
and bump copyright header
view with "hide whitespace changes"
> ScreenshotWindow: inline namespace

- src/ScreenshotWindow.vala
And move other properties to the top
> ScreenshotWindow: Make clipboard a construction property

- meson.build
- src/Application.vala
Doesn't seem like we need all this to continue to support commandline options
> Application: Don't manually handle commandline

- src/ScreenshotWindow.vala
- src/Widgets/SaveDialog.vala
view with "Hide whitespace changes"
> SaveDialog: Inline namespace

- src/ScreenshotWindow.vala
Not necessarily a mouse right?
> ScreenshotWindow: mouse pointer → pointer

- .github/workflows/release.yml
With HdyWindow, we're Odin-only now.
> Release Action: Update to use odin branch

- meson.build
- src/Widgets/SaveDialog.vala
> SaveDialog: replace Gtk.Dialog with Granite.Dialog

- io.elementary.screenshot.yml
Update Sdk to 3.38 and base to 20.08 re-build granite because we need version 6.0.
> Update flatpak manifest

- .github/workflows/merge.yml
We also don't need to run tests here since we run them in CI
> Merge Action: Set branch to daily

- io.elementary.screenshot.yml
No longer needed because of new settings portal
> Flatpak: Remove accountsservice hole

- io.elementary.screenshot.yml
Related to https://github.com/elementary/screenshot/pull/249
> Update runtime to version 7

- meson.build
- src/SaveDialog.vala
Use Gtk.FileDialog instead of Gtk.FileChooserNative which is deprecated in GTK 4.10.
> Use Gtk.FileDialog to choose screenshots folder

- data/screenshot.metainfo.xml.in
- src/SaveDialog.vala
Fixes #306
Based on #305 to prevent conflicts
> Fix screenshot is not saved to the selected folder if changed

- data/screenshot.metainfo.xml.in
- meson.build
> Release 8.0.3

- data/screenshot.metainfo.xml.in
- io.elementary.screenshot.yml
Closes https://github.com/elementary/screenshot/discussions/321
> Flatpak: add device=dri
