src/Application.vala
src/ScreenshotWindow.vala

Solves warnings about having a dialog without a transient parent

Use a Window instead of a dialog without a parent

---

src/ScreenshotWindow.vala

Made all error dialogs use the Granite.MessageDialog widget instead.
Fix for issue #99.
Looks like this now:

Made all error dialogs use Granite.MessageDialog

---

src/ScreenshotWindow.vala

Fixes #50 
Gala's close window animation is 195, so setting the minimum timeout amount to 300 should be plenty of time for the animation to complete

ScreenshotWindow: Increase minimum timeout to 300

---

src/ScreenshotWindow.vala

The spinner will show the correct stored value, but when you take a screenshot the delay will depend on the delay variable which will be zero.

Fix update the delay variable at startup

---

src/Widgets/SaveDialog.vala

Fixes broken checkerboard style in Greenfield

SaveDialog: Use Granite style constants

---

src/Application.vala

For consistency with our other apps
I don't think we need to manually set locale stuff these days with Gtk.Application

Application: Add constructor and remove extra locale

---

src/ScreenshotWindow.vala

Not sure why these args were nullable since we always set all of them and they all have default values in `Application`

ScreenshotWindow: Move from_cmd constructor to top

---

src/Widgets/SaveDialog.vala

Closes #29 . There are still some pending questions about the interaction:
1. should the dialog be closed after the dragging ends? 
2. this only works if the drop target supports images. As such, it does not work when dropping the image into Files or browsers. This limitation also exists with `copy to clipboard` (issue #156 )
As always, thank you for the hard work in Elementary.

Adds drag support for the preview image in Save dialog

---

src/Application.vala

This is required. Not sure why it only causes crashes on some platforms, but it's not optional, so this was indeed a mistake.

Null terminate options array

---

debian/rules

Pretty sure this is outdated since we don't install mo files in meson for extra

Rules: Don't overwrite autoinstall

---

data/screenshot.appdata.xml.in

This is needed for appstream-generator to find the associated desktop file.
See also:
- https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable
- https://github.com/ximion/appstream-generator/issues/88

Add launchable tag to appdata

---

meson.build
src/Application.vala
src/Config.vala.in

Allows to use the translations in Flatpak

i18n: Correctly setup the locales

---

README.md
io.elementary.screenshot.yml
meson.build
src/ScreenshotBackend.vala

We currently rely on Screenshot to play the shutter sound. This means that it needs pulseaudio permissions in Flatpak and depending on the app taking the screenshot you might not get a sound when a screenshot is taken.
In addition, no sound was played when a screenshot was copied directly to the clipboard.
Play the shutter sound in Gala to avoid this problems.
**This PR:** Don't play the shutter after taking a screenshot, Gala will do it for us.
Fix https://github.com/elementary/gala/issues/944
Needs https://github.com/elementary/screenshot/pull/215
Needs https://github.com/elementary/gala/pull/1171

Don't play shutter sound, rely on Gala

---

debian/control

We currently rely on Screenshot to play the shutter sound. This means that it needs pulseaudio permissions in Flatpak and depending on the app taking the screenshot you might not get a sound when a screenshot is taken.
In addition, no sound was played when a screenshot was copied directly to the clipboard.
Play the shutter sound in Gala to avoid this problems.
**This PR:** Remove libcanberra from the Debian package dependencies.
Fix https://github.com/elementary/gala/issues/944
Needs https://github.com/elementary/screenshot/pull/216
Needs https://github.com/elementary/gala/pull/1171

Debian package: Remove libcanberra

---

debian/postinst

This will succeed without being explicit, but I feel like we should be explicit so we're (more) sure we're installing from the right remote, just in case there was a name conflict from another remote.

postinst: Explicitly use AppCenter remote

---

README.md

As other packages are suffixed by `-dev`, it seems more logic to also mention `libhandy-1-dev` as just installing `libhandy-1` is not enough.

README: Fix libhandy-1 package name

---

src/Widgets/SaveDialog.vala

Follow up to #243 
* DRY updating location button
* Use the ellipsis icon and add some spacing
* Use build in translation for Cancel button, translate Select button
* Use FileInfo to get icon and display name for path

SaveDialog: use fileinfo, localize, DRY

---

data/gresource.xml
src/Application.vala
src/ScreenshotWindow.vala

* Use startup for actions and dark style instead of doing it every time we activate
* Use built-in icon loading by setting resource path instead of doing it manually
* Add paths for icons so they work correctly in GTK 4 while here

Application: use startup, builtin icon loading

---

src/ScreenshotWindow.vala
src/Widgets/SaveDialog.vala

* There's no keep above or stick in GTK 4/Wayland so remove those
* Create images separately from radiobuttons. We'll need this in GTK 4 to parent these in the radiobutton and it makes swapping the icon simpler for the whole window screenshot image
* There's no `show_all` or `no_show_all` so change the way we choose not to show redact option. Also present dialog not show_all
* Replace boxes with grids
* ButtonBox is gone in GTK 4, so use a homogeneous box
* Use child property
* We can't position windows ourselves in GTK 4/Wayland so remove that. Gala branch exists to fix this anyways so no loss
* Code style

ScreenshotWindow: GTK 4 prep

---

src/ScreenshotWindow.vala

With this PR and the hacky elementary/gala#1904 I can confirm keep above works on wayland with mutter 46 :partying_face: 
(The issue was that our surface was still null when calling keep above)

Fix the protocol impl

---

data/screenshot.metainfo.xml.in

Needs the `release` tag to actually trigger the workflow

Release 8.0.1

---

src/SaveDialog.vala

Closes #316.
This addresses the issue discussed in issue #316. To summarize what is in that issue, when taking a screenshot and the height is 1/4x or more greater than the width (approx), it will segfault with my setup.
Two solutions were found, but the simplest was in this PR, which is setting a default window height. The other was to use a deprecated method (which is shown in the issue).
As proof of the fix, here is a screenshot whose dimensions will crash the pre-fix app:

patch: fix screenshot crashing when image height exceeds width enough
